// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Kaalay Express Gateway API",
        "description": "API Gateway for Kaalay Express - Ride-hailing and Delivery Platform",
        "version": "1.0.0"
    },
    "host": "app.suqafuran.com",
    "basePath": "/api",
    "schemes": [
        "http",
        "https"
    ],
    "paths": {
        "/health": {
            "get": {
                "tags": ["System"],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy"
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "tags": ["System"],
                "summary": "Readiness check",
                "operationId": "readinessCheck",
                "responses": {
                    "200": {
                        "description": "Service is ready"
                    }
                }
            }
        },
        "/v1/auth/send-otp": {
            "post": {
                "tags": ["Auth"],
                "summary": "Send OTP",
                "operationId": "sendOTP",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "phone": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully"
                    }
                }
            }
        },
        "/v1/auth/verify-otp": {
            "post": {
                "tags": ["Auth"],
                "summary": "Verify OTP",
                "operationId": "verifyOTP",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "phone": {
                                    "type": "string"
                                },
                                "code": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified, JWT token returned"
                    }
                }
            }
        },
        "/v1/orders": {
            "post": {
                "tags": ["Orders"],
                "summary": "Create a new order",
                "operationId": "createOrder",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "Bearer token"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": ["marketplace", "parcel", "grocery", "restaurant", "same_day"]
                                },
                                "pickup_lat": {
                                    "type": "number"
                                },
                                "pickup_lng": {
                                    "type": "number"
                                },
                                "dropoff_lat": {
                                    "type": "number"
                                },
                                "dropoff_lng": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order created successfully"
                    }
                }
            }
        },
        "/v1/payments/initiate": {
            "post": {
                "tags": ["Payments"],
                "summary": "Initiate payment",
                "operationId": "initiatePayment",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "order_id": {
                                    "type": "string"
                                },
                                "amount": {
                                    "type": "number"
                                },
                                "payment_method": {
                                    "type": "string",
                                    "enum": ["mpesa", "card", "wallet"]
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Payment initiated"
                    }
                }
            }
        },
        "/v1/tracking/location": {
            "get": {
                "tags": ["Tracking"],
                "summary": "Get order tracking location",
                "operationId": "getTracking",
                "parameters": [
                    {
                        "name": "order_id",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Current tracking location"
                    }
                }
            }
        }
    }
}
`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "app.suqafuran.com",
	BasePath:    "/api",
	Schemes:     []string{"http", "https"},
	Title:       "Kaalay Express Gateway API",
	Description: "API Gateway for Kaalay Express - Ride-hailing and Delivery Platform",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
