// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Kaalay Express Auth API",
        "description": "Authentication service for Kaalay Express",
        "version": "1.0.0"
    },
    "host": "app.suqafuran.com:8001",
    "basePath": "",
    "schemes": [
        "http",
        "https"
    ],
    "paths": {
        "/health": {
            "get": {
                "tags": ["System"],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy"
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "tags": ["System"],
                "summary": "Readiness check",
                "operationId": "readinessCheck",
                "responses": {
                    "200": {
                        "description": "Service is ready"
                    }
                }
            }
        },
        "/v1/auth/send-otp": {
            "post": {
                "tags": ["Auth"],
                "summary": "Send OTP",
                "operationId": "sendOTP",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "phone": {
                                    "type": "string",
                                    "example": "+254712345678"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully"
                    }
                }
            }
        },
        "/v1/auth/verify-otp": {
            "post": {
                "tags": ["Auth"],
                "summary": "Verify OTP",
                "operationId": "verifyOTP",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "phone": {
                                    "type": "string",
                                    "example": "+254712345678"
                                },
                                "code": {
                                    "type": "string",
                                    "example": "123456"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified, JWT token returned",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "access_token": {
                                            "type": "string"
                                        },
                                        "refresh_token": {
                                            "type": "string"
                                        },
                                        "expires_in": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/me": {
            "get": {
                "tags": ["Auth"],
                "summary": "Get current user",
                "operationId": "getCurrentUser",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "Bearer token"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Current user info"
                    }
                }
            }
        }
    }
}
`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "app.suqafuran.com:8001",
	BasePath:    "",
	Schemes:     []string{"http", "https"},
	Title:       "Kaalay Express Auth API",
	Description: "Authentication service for Kaalay Express",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
