// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Kaalay Express Order API",
        "description": "Order management service for Kaalay Express",
        "version": "1.0.0"
    },
    "host": "app.suqafuran.com:8004",
    "basePath": "",
    "schemes": [
        "http",
        "https"
    ],
    "paths": {
        "/health": {
            "get": {
                "tags": ["System"],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy"
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "tags": ["System"],
                "summary": "Readiness check",
                "operationId": "readinessCheck",
                "responses": {
                    "200": {
                        "description": "Service is ready"
                    }
                }
            }
        },
        "/v1/orders": {
            "post": {
                "tags": ["Orders"],
                "summary": "Create a new order",
                "operationId": "createOrder",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "Bearer token"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": ["marketplace", "parcel", "grocery", "restaurant", "same_day"],
                                    "example": "parcel"
                                },
                                "pickup_lat": {
                                    "type": "number",
                                    "example": -1.2921
                                },
                                "pickup_lng": {
                                    "type": "number",
                                    "example": 36.8219
                                },
                                "pickup_address": {
                                    "type": "string",
                                    "example": "Nairobi CBD, Kenya"
                                },
                                "dropoff_lat": {
                                    "type": "number",
                                    "example": -1.3049
                                },
                                "dropoff_lng": {
                                    "type": "number",
                                    "example": 36.7638
                                },
                                "dropoff_address": {
                                    "type": "string",
                                    "example": "JKIA, Kenya"
                                },
                                "special_instructions": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order created successfully"
                    }
                }
            },
            "get": {
                "tags": ["Orders"],
                "summary": "List user orders",
                "operationId": "listOrders",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "type": "integer",
                        "default": 50
                    },
                    {
                        "name": "offset",
                        "in": "query",
                        "type": "integer",
                        "default": 0
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of orders"
                    }
                }
            }
        },
        "/v1/orders/{id}": {
            "get": {
                "tags": ["Orders"],
                "summary": "Get order details",
                "operationId": "getOrder",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": "Order ID (UUID)"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order details"
                    },
                    "404": {
                        "description": "Order not found"
                    }
                }
            },
            "put": {
                "tags": ["Orders"],
                "summary": "Update order status",
                "operationId": "updateOrderStatus",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "enum": ["pending", "accepted", "preparing", "ready_for_pickup", "driver_assigned", "picked_up", "in_transit", "delivered", "cancelled"]
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order updated"
                    }
                }
            }
        }
    }
}
`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "app.suqafuran.com:8004",
	BasePath:    "",
	Schemes:     []string{"http", "https"},
	Title:       "Kaalay Express Order API",
	Description: "Order management service for Kaalay Express",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
